# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      actions:
        patterns:
          - "@actions/*"
      octokit:
        patterns:
          - "@octokit/*"
      linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      build-and-test:
        patterns:
          - "esbuild"
          - "vitest"
          - "@vitest/*"
          - "nock"
