name: "GitHub Action: Unit Test"

on:
  push:

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Test the Action by running the test suite
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - name: Install dependencies
        run: npm clean-install
     
      - name: Run test suite
        run: npm test
